source 'https://cdn.cocoapods.org'

platform :ios, '15.0'
use_frameworks!

target 'Example_BusinessComponents' do
    pod 'MLBusinessComponents', :path => '../'
    #target 'Example_BusinessComponentsTests' do
    	#inherit! :search_paths
    #end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
end
