source 'https://cdn.cocoapods.org'

platform :ios, '10.0'
use_frameworks!

target 'Example_BusinessComponents' do
    pod 'MLBusinessComponents', :path => '../'
    #target 'Example_BusinessComponentsTests' do
    	#inherit! :search_paths
    #end
end